### PR TITLE
Directory independent extensions

### PR DESCRIPTION
**Pull request by schmunk42**
With this change you can place this extension anywhere and its assets still get registered correctly.

see http://www.yiiframework.com/wiki/105/directory-independent-extensions/ for details

### CODE REVIEW

**Comment by schmunk42** [comment]
Ooops. Sorry duplicate of https://github.com/ifdattic/EChosen/pull/3

**Comment by ifdattic** [comment]
Well it was more of my own fault, no matter what the time for personal projects must always be found.
Thanks for your participation.

**Comment by schmunk42** [comment]
And I found a way to fix this by configuration in the meantime
http://www.yiiframework.com/wiki/457/fixing-extensions-without-modifying-their-code

**Comment by ifdattic** [comment]
Great article, could come in handy.

**Pull request closed without merging**
